# Generated by Django 6.0.1 on 2026-01-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_category_alter_auction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(related_name='watchers', to='auctions.auction'),
        ),
    ]
